stages:
  - build

build_project:
  stage: build
  script:
    - xcodebuild clean -project CIDemo.xcodeproj -scheme CIDemo | xcpretty
    - xcodebuild test -project CIDemo.xcodeproj -scheme CIDemo -destination 'platform=iOS Simulator' | xcpretty -s
  tags:
    - demo
    - ios
